import type { MapEnvironmentObject, MapId, MapInteractable, TrackMap, TrackPoint } from './schema'

const createTree = (id: string, x: number, z: number, scale: number, variant: 'round' | 'cone') => ({
  id,
  position: [x, 0, z] as [number, number, number],
  scale,
  variant,
})

const createGates = (offset: number) => [
  { position: [0, 0, -offset] as [number, number, number], rotation: [0, Math.PI / 2, 0] as [number, number, number] },
  { position: [0, 0, offset] as [number, number, number], rotation: [0, Math.PI / 2, 0] as [number, number, number] },
  { position: [-offset, 0, 0] as [number, number, number] },
  { position: [offset, 0, 0] as [number, number, number] },
]

const createInteractable = (
  id: string,
  kind: MapInteractable['kind'],
  position: [number, number, number],
  size: [number, number, number],
  color: string,
  material: MapInteractable['material'],
  collider: MapInteractable['collider'],
  rotation?: [number, number, number],
): MapInteractable => ({ id, kind, position, size, color, material, collider, rotation })

const createEnvironment = (
  id: string,
  kind: MapEnvironmentObject['kind'],
  position: [number, number, number],
  scale: number,
  color: string,
  speed = 0,
): MapEnvironmentObject => ({ id, kind, position, scale, color, speed })

const basePickups = [
  { id: 's-1', position: [0, 0.8, 0] as [number, number, number], type: 'star' as const },
  { id: 's-2', position: [10, 0.8, -6] as [number, number, number], type: 'star' as const },
  { id: 's-3', position: [-10, 0.8, 8] as [number, number, number], type: 'star' as const },
  { id: 's-4', position: [16, 0.8, 12] as [number, number, number], type: 'star' as const },
  { id: 's-5', position: [-18, 0.8, -14] as [number, number, number], type: 'star' as const },
  { id: 'r-1', position: [20, 0.8, -3] as [number, number, number], type: 'repair' as const },
  { id: 'r-2', position: [-20, 0.8, 4] as [number, number, number], type: 'repair' as const },
  { id: 'p-1', position: [12, 0.8, 16] as [number, number, number], type: 'part' as const },
  { id: 'p-2', position: [-14, 0.8, -18] as [number, number, number], type: 'part' as const },
]

const baseDestructiblePoints: [number, number, number][] = [
  [0, 0.7, 20],
  [0, 0.7, -20],
  [20, 0.7, 0],
  [-20, 0.7, 0],
  [15, 0.7, 15],
  [15, 0.7, -15],
  [-15, 0.7, 15],
  [-15, 0.7, -15],
  [6, 0.7, 20],
  [-6, 0.7, -20],
]

const orbitalPath: TrackPoint[] = [
  [14, -58],
  [52, -46],
  [61, -12],
  [56, 26],
  [33, 55],
  [2, 67],
  [-40, 56],
  [-59, 24],
  [-56, -22],
  [-32, -52],
]

const titanPath: TrackPoint[] = [
  [16, -39],
  [44, -33],
  [56, -8],
  [47, 24],
  [18, 45],
  [-16, 44],
  [-46, 26],
  [-57, -6],
  [-42, -35],
  [-10, -50],
]

const rampPath: TrackPoint[] = [
  [-4, -92],
  [4, -92],
  [4, 92],
  [-4, 92],
]

const rampPickups = [
  { id: 'ramp-s-1', position: [0, -16.6, -70] as [number, number, number], type: 'star' as const },
  { id: 'ramp-s-2', position: [0, -8.9, -38] as [number, number, number], type: 'star' as const },
  { id: 'ramp-s-3', position: [0, -1.2, -6] as [number, number, number], type: 'star' as const },
  { id: 'ramp-s-4', position: [0, 6.5, 26] as [number, number, number], type: 'star' as const },
  { id: 'ramp-s-5', position: [0, 14.2, 58] as [number, number, number], type: 'star' as const },
  { id: 'ramp-r-1', position: [1.8, -4.8, -22] as [number, number, number], type: 'repair' as const },
  { id: 'ramp-r-2', position: [-1.8, 10.4, 42] as [number, number, number], type: 'repair' as const },
  { id: 'ramp-p-1', position: [2.2, 1.8, 6] as [number, number, number], type: 'part' as const },
  { id: 'ramp-p-2', position: [-2.2, 12.8, 52] as [number, number, number], type: 'part' as const },
]

export const MAP_ORDER: MapId[] = ['orbital', 'gaia', 'titan', 'procedural']

export const MAP_LABELS: Record<MapId, string> = {
  orbital: 'Orbital Rift',
  gaia: 'Gaia Megaring',
  titan: 'Titan Brakefield',
  ramp: 'Sky Ramp',
  procedural: 'Nebula Loop',
}

export const FIXED_MAPS: Record<Exclude<MapId, 'procedural'>, TrackMap> = {
  orbital: {
    schemaVersion: '3.0.0',
    id: 'orbital',
    sourceId: 'orbital',
    label: MAP_LABELS.orbital,
    shape: 'path',
    worldHalf: 82,
    outerHalf: 0,
    innerHalf: 0,
    roadWidth: 12,
    laneCount: 2,
    laneWidth: 6,
    detailDensity: 2.2,
    roadPath: orbitalPath,
    startPosition: [orbitalPath[0][0], 0.38, orbitalPath[0][1]],
    startYaw: Math.atan2(orbitalPath[1][0] - orbitalPath[0][0], orbitalPath[1][1] - orbitalPath[0][1]),
    gravity: [0, -4.25, 0],
    terrain: {
      profile: 'craggy',
      amplitude: 11.8,
      frequency: 0.013,
    },
    materialZones: [
      { id: 'global-dust', shape: 'global', material: 'dust' },
      { id: 'track-regolith', shape: 'path-band', material: 'regolith', width: 13.5 },
      { id: 'ice-pocket-north', shape: 'circle', material: 'ice', center: [22, 44], radius: 10 },
      { id: 'ice-pocket-west', shape: 'circle', material: 'ice', center: [-41, -11], radius: 8.5 },
    ],
    materialTuning: {
      regolith: { tractionMultiplier: 0.95, dragMultiplier: 1.08, topSpeedMultiplier: 0.98 },
      dust: { tractionMultiplier: 0.82, dragMultiplier: 1.18, topSpeedMultiplier: 0.92 },
      ice: { tractionMultiplier: 0.55, dragMultiplier: 0.88, topSpeedMultiplier: 1.02 },
    },
    spawnRules: {
      pickups: {
        initial: basePickups,
        minCounts: { star: 5, repair: 3, part: 2 },
        bonusRepairChance: 0.42,
        bonusPartChance: 0.35,
      },
      hazards: {
        critters: {
          enabled: true,
          count: 10,
          breakSpeed: 2.8,
          hitRadius: 1.15,
          hitCheckInterval: 0.08,
          respawnSeconds: 5.2,
        },
        destructibles: {
          initialCount: 6,
          spawnPoints: baseDestructiblePoints,
          breakSpeed: 5.8,
          respawnSeconds: 3.8,
          palette: ['#d39d58', '#be8744', '#c19352', '#9d7241'],
        },
      },
      obstacles: {
        static: [],
        movable: [],
      },
    },
    gates: [
      { position: [53, 0, -29], rotation: [0, 2.84, 0] },
      { position: [40, 0, 42], rotation: [0, 2.17, 0] },
      { position: [-22, 0, 61], rotation: [0, 1.12, 0] },
      { position: [-57, 0, -2], rotation: [0, 0.36, 0] },
      { position: [-24, 0, -53], rotation: [0, -0.96, 0] },
    ],
    trees: [
      createTree('orbital-t1', -69, -63, 1.24, 'cone'),
      createTree('orbital-t2', -66, 63, 1.12, 'round'),
      createTree('orbital-t3', 70, 63, 1.16, 'cone'),
      createTree('orbital-t4', 68, -64, 1.11, 'round'),
      createTree('orbital-t5', -55, 18, 1.05, 'round'),
      createTree('orbital-t6', 58, -20, 1.05, 'cone'),
    ],
    interactables: [
      createInteractable('orb-ramp-a', 'ramp', [27, 0.6, -16], [8.5, 1.1, 4.2], '#b98a59', 'medium', 'fixed', [0, -0.4, 0]),
      createInteractable('orb-ramp-b', 'ramp', [-28, 0.6, 15], [8.5, 1.1, 4.2], '#b98a59', 'medium', 'fixed', [0, 2.7, 0]),
      createInteractable('orb-tower-a', 'tower', [58, 4.2, 8], [8, 8.4, 8], '#777f8c', 'hard', 'fixed'),
      createInteractable('orb-tower-b', 'tower', [-56, 4.2, -10], [8, 8.4, 8], '#777f8c', 'hard', 'fixed'),
      createInteractable('orb-crate-a', 'crate', [8, 0.55, 29], [1.1, 1.1, 1.1], '#c58f45', 'medium', 'dynamic'),
      createInteractable('orb-crate-b', 'crate', [-12, 0.55, -31], [1.1, 1.1, 1.1], '#c58f45', 'medium', 'dynamic'),
      createInteractable('orb-barrier-a', 'barrier', [44, 0.6, 18], [10, 1.2, 1], '#d86046', 'hard', 'fixed', [0, 0.8, 0]),
      createInteractable('orb-barrier-b', 'barrier', [-44, 0.6, -20], [10, 1.2, 1], '#d86046', 'hard', 'fixed', [0, -2.3, 0]),
    ],
    environmentObjects: [
      createEnvironment('orb-sun', 'sun', [74, 84, -42], 9.2, '#ffd58d'),
      createEnvironment('orb-cloud-a', 'cloud', [-24, 57, -66], 1.8, '#f1f8ff', 0.62),
      createEnvironment('orb-cloud-b', 'cloud', [52, 53, 41], 1.45, '#ecf6ff', 0.45),
      createEnvironment('orb-bird-a', 'bird', [8, 36, -8], 1.2, '#2e3b4c', 1.45),
      createEnvironment('orb-bird-b', 'bird', [-18, 34, 25], 1.05, '#334254', 1.25),
    ],
  },
  gaia: {
    schemaVersion: '3.0.0',
    id: 'gaia',
    sourceId: 'gaia',
    label: MAP_LABELS.gaia,
    shape: 'ring',
    worldHalf: 88,
    outerHalf: 50,
    innerHalf: 24,
    roadWidth: 26,
    laneCount: 4,
    laneWidth: 6.5,
    detailDensity: 1.35,
    roadPath: [],
    startPosition: [0, 0.38, 41],
    startYaw: Math.PI / 2,
    gravity: [0, -12, 0],
    terrain: {
      profile: 'rolling',
      amplitude: 2.1,
      frequency: 0.026,
    },
    materialZones: [
      { id: 'global-basalt', shape: 'global', material: 'basalt' },
      { id: 'track-asphalt', shape: 'ring-band', material: 'asphalt', minHalf: 24, maxHalf: 50 },
      { id: 'inner-ice-patch', shape: 'circle', material: 'ice', center: [0, 0], radius: 7.4 },
    ],
    materialTuning: {
      asphalt: { tractionMultiplier: 1, dragMultiplier: 1, topSpeedMultiplier: 1 },
      basalt: { tractionMultiplier: 0.9, dragMultiplier: 1.1, topSpeedMultiplier: 0.95 },
      ice: { tractionMultiplier: 0.62, dragMultiplier: 0.9, topSpeedMultiplier: 1.02 },
    },
    spawnRules: {
      pickups: {
        initial: basePickups,
        minCounts: { star: 5, repair: 3, part: 2 },
        bonusRepairChance: 0.45,
        bonusPartChance: 0.32,
      },
      hazards: {
        critters: {
          enabled: false,
          count: 0,
          breakSpeed: 3.2,
          hitRadius: 1.05,
          hitCheckInterval: 0.08,
          respawnSeconds: 4.2,
        },
        destructibles: {
          initialCount: 5,
          spawnPoints: baseDestructiblePoints,
          breakSpeed: 6.5,
          respawnSeconds: 3.2,
          palette: ['#d39d58', '#be8744', '#c19352', '#9d7241'],
        },
      },
      obstacles: {
        static: [],
        movable: [],
      },
    },
    gates: createGates(36),
    trees: [
      createTree('gaia-t1', -72, -69, 1.12, 'cone'),
      createTree('gaia-t2', -70, 69, 1.07, 'cone'),
      createTree('gaia-t3', 72, -69, 1.12, 'cone'),
      createTree('gaia-t4', 70, 70, 1.07, 'cone'),
      createTree('gaia-t5', -58, -12, 0.95, 'round'),
      createTree('gaia-t6', 59, 12, 0.95, 'round'),
      createTree('gaia-t7', -18, 60, 0.92, 'round'),
      createTree('gaia-t8', 18, -58, 0.92, 'round'),
    ],
    interactables: [
      createInteractable('gaia-tower-nw', 'tower', [-53, 3.8, -53], [8.5, 7.6, 8.5], '#757e8b', 'hard', 'fixed'),
      createInteractable('gaia-tower-ne', 'tower', [53, 3.8, -53], [8.5, 7.6, 8.5], '#757e8b', 'hard', 'fixed'),
      createInteractable('gaia-tower-sw', 'tower', [-53, 3.8, 53], [8.5, 7.6, 8.5], '#757e8b', 'hard', 'fixed'),
      createInteractable('gaia-tower-se', 'tower', [53, 3.8, 53], [8.5, 7.6, 8.5], '#757e8b', 'hard', 'fixed'),
      createInteractable('gaia-ramp-w', 'ramp', [-37, 0.55, 0], [9.5, 1.1, 4.5], '#b98a59', 'medium', 'fixed', [0, Math.PI / 2, 0]),
      createInteractable('gaia-ramp-e', 'ramp', [37, 0.55, 0], [9.5, 1.1, 4.5], '#b98a59', 'medium', 'fixed', [0, -Math.PI / 2, 0]),
      createInteractable('gaia-crate-a', 'crate', [0, 0.55, -31], [1.2, 1.2, 1.2], '#c58f45', 'medium', 'dynamic'),
      createInteractable('gaia-crate-b', 'crate', [0, 0.55, 31], [1.2, 1.2, 1.2], '#c58f45', 'medium', 'dynamic'),
      createInteractable('gaia-barrier-a', 'barrier', [0, 0.65, -47], [12, 1.3, 1], '#d86046', 'hard', 'fixed'),
      createInteractable('gaia-barrier-b', 'barrier', [0, 0.65, 47], [12, 1.3, 1], '#d86046', 'hard', 'fixed'),
    ],
    environmentObjects: [
      createEnvironment('gaia-sun', 'sun', [-76, 78, 46], 8.6, '#ffe39d'),
      createEnvironment('gaia-cloud-a', 'cloud', [26, 52, -63], 1.55, '#f4fbff', 0.56),
      createEnvironment('gaia-cloud-b', 'cloud', [-48, 57, 31], 1.7, '#eef8ff', 0.42),
      createEnvironment('gaia-bird-a', 'bird', [10, 34, 14], 1.1, '#303d4f', 1.32),
      createEnvironment('gaia-bird-b', 'bird', [-12, 31, -18], 1.03, '#344256', 1.46),
    ],
  },
  titan: {
    schemaVersion: '3.0.0',
    id: 'titan',
    sourceId: 'titan',
    label: MAP_LABELS.titan,
    shape: 'path',
    worldHalf: 78,
    outerHalf: 0,
    innerHalf: 0,
    roadWidth: 13.5,
    laneCount: 3,
    laneWidth: 4.5,
    detailDensity: 2.4,
    roadPath: titanPath,
    startPosition: [titanPath[0][0], 0.38, titanPath[0][1]],
    startYaw: Math.atan2(titanPath[1][0] - titanPath[0][0], titanPath[1][1] - titanPath[0][1]),
    gravity: [0, -18.5, 0],
    terrain: {
      profile: 'rolling',
      amplitude: 5.8,
      frequency: 0.016,
    },
    materialZones: [
      { id: 'global-regolith', shape: 'global', material: 'regolith' },
      { id: 'track-basalt', shape: 'path-band', material: 'basalt', width: 15 },
      { id: 'brake-zone-east', shape: 'circle', material: 'dust', center: [44, -8], radius: 8 },
      { id: 'brake-zone-west', shape: 'circle', material: 'dust', center: [-46, 26], radius: 8 },
    ],
    materialTuning: {
      basalt: { tractionMultiplier: 1.04, dragMultiplier: 1.18, topSpeedMultiplier: 0.9 },
      regolith: { tractionMultiplier: 0.86, dragMultiplier: 1.2, topSpeedMultiplier: 0.9 },
      dust: { tractionMultiplier: 0.75, dragMultiplier: 1.28, topSpeedMultiplier: 0.84 },
    },
    spawnRules: {
      pickups: {
        initial: basePickups,
        minCounts: { star: 5, repair: 3, part: 2 },
        bonusRepairChance: 0.5,
        bonusPartChance: 0.36,
      },
      hazards: {
        critters: {
          enabled: true,
          count: 6,
          breakSpeed: 3,
          hitRadius: 1.05,
          hitCheckInterval: 0.08,
          respawnSeconds: 3.8,
        },
        destructibles: {
          initialCount: 7,
          spawnPoints: baseDestructiblePoints,
          breakSpeed: 5.4,
          respawnSeconds: 2.8,
          palette: ['#d39d58', '#be8744', '#c19352', '#9d7241'],
        },
      },
      obstacles: {
        static: [],
        movable: [],
      },
    },
    gates: [
      { position: [49, 0, -20], rotation: [0, 2.92, 0] },
      { position: [49, 0, 12], rotation: [0, 2.33, 0] },
      { position: [11, 0, 46], rotation: [0, 1.58, 0] },
      { position: [-48, 0, 12], rotation: [0, 0.32, 0] },
      { position: [-28, 0, -44], rotation: [0, -0.76, 0] },
    ],
    trees: [
      createTree('titan-t1', -65, -61, 1.24, 'round'),
      createTree('titan-t2', -62, 63, 1.14, 'round'),
      createTree('titan-t3', 66, -62, 1.24, 'round'),
      createTree('titan-t4', 63, 64, 1.14, 'round'),
      createTree('titan-t5', -53, 15, 1.03, 'cone'),
      createTree('titan-t6', 52, -17, 1.03, 'cone'),
      createTree('titan-t7', -22, -57, 0.98, 'round'),
      createTree('titan-t8', 24, 58, 0.98, 'round'),
    ],
    interactables: [
      createInteractable('titan-ramp-a', 'ramp', [28, 0.6, -18], [10, 1.2, 4.8], '#b88958', 'medium', 'fixed', [0, -0.5, 0]),
      createInteractable('titan-ramp-b', 'ramp', [-30, 0.6, 19], [10, 1.2, 4.8], '#b88958', 'medium', 'fixed', [0, 2.5, 0]),
      createInteractable('titan-ramp-c', 'ramp', [0, 0.6, 40], [9, 1.15, 4.4], '#b88958', 'medium', 'fixed', [0, 1.5, 0]),
      createInteractable('titan-block-a', 'block', [55, 1.3, 20], [13, 2.6, 8], '#6f747f', 'hard', 'fixed'),
      createInteractable('titan-block-b', 'block', [-57, 1.3, -16], [13, 2.6, 8], '#6f747f', 'hard', 'fixed'),
      createInteractable('titan-crate-a', 'crate', [20, 0.58, 5], [1.2, 1.2, 1.2], '#c58f45', 'medium', 'dynamic'),
      createInteractable('titan-crate-b', 'crate', [-18, 0.58, -6], [1.2, 1.2, 1.2], '#c58f45', 'medium', 'dynamic'),
      createInteractable('titan-crate-c', 'crate', [10, 0.58, -30], [1.2, 1.2, 1.2], '#c58f45', 'medium', 'dynamic'),
      createInteractable('titan-barrier-a', 'barrier', [42, 0.65, -12], [10, 1.3, 1], '#d75a40', 'hard', 'fixed', [0, 0.4, 0]),
      createInteractable('titan-barrier-b', 'barrier', [-41, 0.65, 12], [10, 1.3, 1], '#d75a40', 'hard', 'fixed', [0, -2.7, 0]),
    ],
    environmentObjects: [
      createEnvironment('titan-sun', 'sun', [82, 88, -28], 9.4, '#ffd184'),
      createEnvironment('titan-cloud-a', 'cloud', [40, 55, -62], 1.65, '#f4f9ff', 0.6),
      createEnvironment('titan-cloud-b', 'cloud', [-52, 58, 38], 1.75, '#ebf4ff', 0.4),
      createEnvironment('titan-bird-a', 'bird', [0, 37, 0], 1.25, '#2e3948', 1.5),
      createEnvironment('titan-bird-b', 'bird', [22, 33, -24], 1.08, '#344152', 1.25),
      createEnvironment('titan-bird-c', 'bird', [-24, 35, 29], 1.08, '#344152', 1.38),
    ],
  },
  ramp: {
    schemaVersion: '3.0.0',
    id: 'ramp',
    sourceId: 'ramp',
    label: MAP_LABELS.ramp,
    shape: 'path',
    worldHalf: 100,
    outerHalf: 0,
    innerHalf: 0,
    roadWidth: 24,
    laneCount: 2,
    laneWidth: 12,
    detailDensity: 0.95,
    roadPath: rampPath,
    startPosition: [0, 0.38, -84],
    startYaw: 0,
    gravity: [0, -10.2, 0],
    terrain: {
      profile: 'rolling',
      amplitude: 22,
      frequency: 0.01,
    },
    materialZones: [
      { id: 'global-asphalt', shape: 'global', material: 'asphalt' },
    ],
    materialTuning: {
      asphalt: { tractionMultiplier: 1.03, dragMultiplier: 1, topSpeedMultiplier: 1 },
    },
    spawnRules: {
      pickups: {
        initial: rampPickups,
        minCounts: { star: 5, repair: 2, part: 2 },
        bonusRepairChance: 0.25,
        bonusPartChance: 0.2,
      },
      hazards: {
        critters: {
          enabled: false,
          count: 0,
          breakSpeed: 3.1,
          hitRadius: 1.05,
          hitCheckInterval: 0.08,
          respawnSeconds: 4.2,
        },
        destructibles: {
          initialCount: 0,
          spawnPoints: [],
          breakSpeed: 6.2,
          respawnSeconds: 4.4,
          palette: ['#d39d58', '#be8744', '#c19352', '#9d7241'],
        },
      },
      obstacles: {
        static: [],
        movable: [],
      },
    },
    gates: [
      { position: [0, -13, -56], rotation: [0, Math.PI / 2, 0] },
      { position: [0, -5.4, -24], rotation: [0, Math.PI / 2, 0] },
      { position: [0, 2.2, 8], rotation: [0, Math.PI / 2, 0] },
      { position: [0, 9.8, 40], rotation: [0, Math.PI / 2, 0] },
      { position: [0, 17.4, 72], rotation: [0, Math.PI / 2, 0] },
    ],
    trees: [
      createTree('ramp-t1', -72, -76, 1.1, 'cone'),
      createTree('ramp-t2', 74, -74, 1.1, 'round'),
      createTree('ramp-t3', -76, 74, 1.1, 'round'),
      createTree('ramp-t4', 72, 76, 1.1, 'cone'),
    ],
    interactables: [],
    environmentObjects: [
      createEnvironment('ramp-sun', 'sun', [74, 86, -44], 8.8, '#ffe0a3'),
      createEnvironment('ramp-cloud-a', 'cloud', [-32, 58, -66], 1.55, '#eff8ff', 0.5),
      createEnvironment('ramp-cloud-b', 'cloud', [36, 54, 52], 1.42, '#eff8ff', 0.42),
    ],
  },
}
